server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://consumer-qa-loyaltysystem-pgsql-0.postgres.database.chinacloudapi.cn/loyaltydata
    username: pgadmin@consumer-qa-loyaltysystem-pgsql-0
    password: p5mWLQ$Pe4dI0Ld4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: update
    show-sql: true
